Algoritmo "Conversor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2023
Var
// Seção de Declarações das variáveis 
angulo, s: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         escreva ("informe um angulo: ")
         leia(angulo)
         S<- sen(GraupRad(angulo))
         Escreva("O seno de ", angulo, " E igual a ", S)


Fimalgoritmo