Algoritmo "semnome"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2023
 Var
// Seção de Declarações das variáveis 
valor, parcelas, juros: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("qual o valor do emprestimo? ")
   leia (valor)
   escreva ("em quantas parcelas voce pretende pagar? ")
   leia (parcelas)
   juros<-(valor*20)/100
   escreva("o valor do emprestimo com juros + parcelas ficara: ",(valor + juros)/parcelas)

Fimalgoritmo